/**
 * Writes `js/config.deploy.js` from environment variables (Vercel / CI).
 * Set in Vercel: Project → Settings → Environment Variables:
 *   SUPABASE_URL       = https://xxxx.supabase.co
 *   SUPABASE_ANON_KEY  = eyJ... (anon / public key only)
 */
import { writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const out = join(__dirname, '..', 'js', 'config.deploy.js');

const url = process.env.SUPABASE_URL || '';
const key = process.env.SUPABASE_ANON_KEY || '';

const body = `/* Generated by scripts/inject-config.mjs — do not commit */
export const SUPABASE_URL = ${JSON.stringify(url)};
export const SUPABASE_ANON_KEY = ${JSON.stringify(key)};
`;

writeFileSync(out, body, 'utf8');
if (url && key) {
  console.log('inject-config: wrote js/config.deploy.js (credentials present).');
} else {
  console.log('inject-config: wrote js/config.deploy.js (empty — set SUPABASE_URL + SUPABASE_ANON_KEY on Vercel).');
}
